insert into products(code, name, description, image_url, price)
values ('P115', 'Pride and Prejudice',
        'A romantic novel of manners that features the character development of Elizabeth Bennet, the dynamic protagonist.',
        'https://images.gr-assets.com/books/1320399351l/1885.jpg', 19.99),
       ('P116', '1984',
        'A dystopian novel by English novelist George Orwell that tells the story of Winston Smith and his disillusionment with the totalitarian regime he lives under.',
        'https://images.gr-assets.com/books/1348990566l/5470.jpg', 21.00),
       ('P117', 'Harry Potter and the Sorcerer''s Stone',
        'The first novel in the Harry Potter series and Rowling''s debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage.',
        'https://images.gr-assets.com/books/1474154022l/3.jpg', 22.50),
       ('P118', 'The Lord of the Rings',
        'An epic high-fantasy novel written by English author and scholar J. R. R. Tolkien.',
        'https://images.gr-assets.com/books/1566425108i/33.jpg', 35.00),
       ('P119', 'The Great Gatsby',
        'A novel by American writer F. Scott Fitzgerald that follows a cast of characters living in the fictional towns of West Egg and East Egg on prosperous Long Island in the summer of 1922.',
        'https://images.gr-assets.com/books/1490528560l/4671.jpg', 18.00),
       ('P120', 'Catcher in the Rye',
        'A novel by J. D. Salinger, partially published in serial form in 1945–1946 and as a novel in 1951.',
        'https://images.gr-assets.com/books/1398034300l/5107.jpg', 15.40),
       ('P121', 'Moby Dick',
        'An 1851 novel by American writer Herman Melville. The book is the sailor Ishmael''s narrative of the obsessive quest of Ahab, captain of the whaling ship Pequod.',
        'https://images.gr-assets.com/books/1327940656l/153747.jpg', 17.80),
       ('P122', 'War and Peace',
        'A novel by the Russian author Leo Tolstoy, first published from 1865 to 1869. It is regarded as one of Tolstoy''s finest literary achievements.',
        'https://images.gr-assets.com/books/1413215930l/656.jpg', 20.00),
       ('P123', 'The Catcher in the Rye',
        'A story about a few days in the life of a troubled teenager, Holden Caulfield, and his experiences in New York City.',
        'https://images.gr-assets.com/books/1398034300l/5107.jpg', 15.40),
       ('P124', 'Brave New World',
        'A dystopian social science fiction novel and a prophetic work by English author Aldous Huxley.',
        'https://images.gr-assets.com/books/1575509280i/5129.jpg', 18.20),
       ('P125', 'Crime and Punishment',
        'A novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866.',
        'https://images.gr-assets.com/books/1382846449l/7144.jpg', 19.95),
       ('P126', 'Animal Farm',
        'A political fable based on the events of Russia''s Bolshevik revolution and the betrayal of the cause by Joseph Stalin.',
        'https://images.gr-assets.com/books/1424037542l/7613.jpg', 12.00),
       ('P127', 'The Hobbit',
        'A children''s fantasy novel by English author J. R. R. Tolkien. It was published on 21 September 1937 to wide critical acclaim.',
        'https://images.gr-assets.com/books/1372847500l/5907.jpg', 14.20),
       ('P128', 'Little Women',
        'A novel by American author Louisa May Alcott, which was originally published in two volumes in 1868 and 1869.',
        'https://images.gr-assets.com/books/1562690475l/1934.jpg', 16.50),
       ('P129', 'Jane Eyre',
        'A novel by English writer Charlotte Brontë, published under the pen name "Currer Bell", on 16 October 1847.',
        'https://images.gr-assets.com/books/1327867269l/10210.jpg', 15.80),
       ('P130', 'Fahrenheit 451',
        'A dystopian novel by American writer Ray Bradbury, published in 1953. It is regarded as one of his best works.',
        'https://images.gr-assets.com/books/1351643740l/4381.jpg', 13.60),
       ('P131', 'The Adventures of Huckleberry Finn',
        'A novel by Mark Twain, first published in the United Kingdom in December 1884 and in the United States in February 1885.',
        'https://images.gr-assets.com/books/1546096879i/2956.jpg', 12.50),
       ('P132', 'Slaughterhouse-Five',
        'A science fiction-infused anti-war novel by Kurt Vonnegut about the World War II experiences and journeys through time of Billy Pilgrim.',
        'https://images.gr-assets.com/books/1440319389l/4981.jpg', 14.00),
       ('P133', 'Don Quixote',
        'A Spanish novel by Miguel de Cervantes. Its full title is The Ingenious Gentleman Don Quixote of La Mancha.',
        'https://images.gr-assets.com/books/1546112331i/3836.jpg', 18.90),
       ('P134', 'The Brothers Karamazov',
        'A philosophical novel set in 19th-century Russia, that enters deeply into the ethical debates of God, free will, and morality.',
        'https://images.gr-assets.com/books/1427728126l/4934.jpg', 21.00);
